// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLHSBpgjxLTVCG_7A_EWGYdEBhLrkY4I0',
    appId: '1:284556188040:web:c827bbd3bc6a4f386c023d',
    messagingSenderId: '284556188040',
    projectId: 'project-c7663',
    authDomain: 'project-c7663.firebaseapp.com',
    storageBucket: 'project-c7663.appspot.com',
    measurementId: 'G-3TBNN8PDLL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACSjpfhOgFl6_hKhcjgHTQRMu2FkrzP9Y',
    appId: '1:284556188040:android:b01322d87ded84996c023d',
    messagingSenderId: '284556188040',
    projectId: 'project-c7663',
    storageBucket: 'project-c7663.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG9h1g1TwCOkF3VnGwcDO0iMlIPYoNh6Y',
    appId: '1:284556188040:ios:835dd02ad24b2a776c023d',
    messagingSenderId: '284556188040',
    projectId: 'project-c7663',
    storageBucket: 'project-c7663.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
